const actionTypes = Object.freeze({
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FILTER_PRODUCTS_BY_SIZE: "FILTER_PRODUCTS_BY_SIZE",
  ORDER_PRODUCTS_BY_SIZE: "ORDER_PRODUCTS_BY_SIZE"
 
});

export default actionTypes;
